config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'top_page#index'
  get 'terms', to: 'top_page#terms'
  get 'aboutus', to: 'top_page#aboutus'
  resources :reviews, only: [:index,:new,:create,:show, :edit, :update, :destroy]
  resources :mypages, only: [:index]
  resources :search, only: [:index] do
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/image_attach_validator.rb
class ImageAttachValidator < ActiveModel::Validator
  def validate(record)
    unless record.image.attached?
      record.errors[:image] << 'you need to attach some image'
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  include ActiveModel::Validations
  belongs_to :user
  has_one_attached :image
  validates :name, :maker, :text, :sharpness, :richness, :sourness, :sweetness, :bitterness, :image, presence: true
  validates :name, :maker, length: { maximum: 20 }
  validates :text, length: { maximum: 140 }
  
  validates_with ImageAttachValidator
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :reviews
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  protected

  def configure_permitted_parameters
    added_attrs = [ :nickname, :email, :password, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review , only: [:edit,:update,:destroy,:show]
  skip_before_action :authenticate_user!, only: [:show,:index]

  def show
    gon.score = ["#{@review.sharpness}", "#{@review.richness}", "#{@review.sourness}", "#{@review.bitterness}", "#{@review.sweetness}"]
  end

  def index
    @reviews = Review.limit(4).order(" created_at DESC ")
    # @your_reviews = Review.limit(4).order(" created_at DESC ").where(user_id: current_user.id)
    # @highest_reviews Review.limit(4).order(" sweetness + sourness + bitterness + sharpness + richness ASC ")
    # a = [:sweetness, :sourness, :bitterness, :sharpness, :richness]
    # @total = a.sum

    @search = Review.ransack(params[:q])
    @search_result = @search.result
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    if @review.save
      redirect_to reviews_path
    else
      render :new
    end
  end

  def edit
    if @review.user_id != current_user.id
      redirect_to reviews_path(@review)
    end
  end

  def update
    redirect_to reviews_path if @review.user_id != current_user.id
    if @review.update(review_params)
      redirect_to reviews_path
    else
      render 'edit'
    end
  end

  def destroy
    if @review.user_id == current_user.id
      @review.destroy
      redirect_to reviews_path
    end
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:name, :maker, :text, :sharpness, :richness, :sourness, :bitterness, :sweetness, :user_id, :image).merge(user_id: current_user.id)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    # @reviews = Review.all
    # 検索オブジェクト
    @search = Review.ransack(params[:q])
    # 検索結果
    @search_result = @search.result
  end
end

app/controllers/top_page_controller.rb
class TopPageController < ApplicationController
  skip_before_action :authenticate_user!
  
  def terms
    
  end

  def aboutus
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/top_page_helper.rb
module TopPageHelper
end

app/views/layouts/_error.html.haml
- if model.errors.any?
  .alert.alert-warning
    %ul
      - model.errors.full_messages.each do |message|
        %li= message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BeerLog
    = csrf_meta_tags
    = csp_meta_tag
    = include_gon
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/mypages/index.html.haml
.wrapper
  = render "templete/header"
  .mypage-main
    .mypage-main__box
  = render "templete/footer"

app/views/reviews/edit.html.haml
.wrapper
  = render "templete/header"
  .review-detail
    = form_with model: @review, url: review_path, class: "review-form", method: :patch do |f|
      = render 'layouts/error', model: f.object
      .review-images
      = f.label :image, "画像", class: "review-label"
      %span.required *
      = f.file_field :image, class:"file"
      .review-score
        .review-score__forms
          .score-box
            %h3.review
              = f.label :name, "製品名", class: "review-label"
              %span.required *
            = f.text_field :name, placeholder: "例) 一番搾り", type: "text", value: "", style: "width:100%; box-sizing:border-box"
          .score-box
            %h3.review
              = f.label :maker, "メーカー", class: "review-label"
              %span.required *
            = f.text_field :maker, placeholder: "例) キリンビール", type: "text", value: "", style: "width:100%; box-sizing:border-box"
          .score-box
            %h3.review
              = f.label :text, "レビュー本文", class: "review-label"
              %span.required *
            = f.text_area :text, placeholder: "例) 男は黙ってサッポロビール", type: "text", value: "", style: "width:100%; min-height:100px; resize:vertical; box-sizing:border-box", cols: "40", rows: "4"
          .range
            %h3.review
              = f.label :sharpness, "キレ", class: "review-label"
              %span.required *
            = f.range_field :sharpness, min: "0", max: "10", step: "1", value: "5", style: "width:95%; box-sizing:border-box", list: "tickmarks"
            %span#value 5
            %datalist{id: "tickmarks"}
              %option{value: "0", label: "0"}
              %option{value: "1"}
              %option{value: "2"}
              %option{value: "3"}
              %option{value: "4"}
              %option{value: "5", label: "5"}
              %option{value: "6"}
              %option{value: "7"}
              %option{value: "8"}
              %option{value: "9"}
              %option{value: "10", label: "10"}
          .range
            %h3.review
              = f.label :richness, "コク", class: "review-label"
              %span.required *
            = f.range_field :richness, min: "0", max: "10", step: "1", value: "5", style: "width:95%; box-sizing:border-box;", list: "tickmarks"
            %span#value 5
          .range
            %h3.review
              = f.label :sourness, "酸味", class: "review-label"
              %span.required *
            = f.range_field :sourness, min: "0", max: "10", step: "1", value: "5", style: "width:95%; box-sizing:border-box", list: "tickmarks"
            %span#value 5
          .range
            %h3.review
              = f.label :bitterness, "苦味", class: "review-label"
              %span.required *
            = f.range_field :bitterness, min: "0", max: "10", step: "1", value: "5", style: "width:95%; box-sizing:border-box", list: "tickmarks"
            %span#value 5
          .range
            %h3.review
              = f.label :sweetness, "甘み", class: "review-label"
              %span.required *
            = f.range_field :sweetness, min: "0", max: "10", step: "1", value: "5", style: "width:95%; box-sizing:border-box", list: "tickmarks"
            %span#value 5
          .submit-btn
            = f.submit "投稿", class: "review-submit"
            .back-btn
              = link_to "戻る", reviews_path
  = render "templete/footer"
  :javascript
    var elem = document.getElementsByClassName('range');
      var rangeValue = function (elem, target) {
        return function(evt){
        target.innerHTML = elem.value;
        }
      }
    for(var i = 0, max = elem.length; i < max; i++){
      bar = elem[i].getElementsByTagName('input')[0];
      target = elem[i].getElementsByTagName('span')[0];
      bar.addEventListener('input', rangeValue(bar, target));
    }

app/views/reviews/index.html.haml
.wrapper
  = render "templete/header"
  .banner
    .search-bar
      .search-bar__text chug it
      .search-bar__box
        .search-bar__box--form
          = search_form_for @search, url: search_index_path do |f|
            = f.text_field :name_or_maker_or_text_cont, placeholder: '検索するビールを入力...'
            = f.submit ("検索") , class: 'search-btn'
  .main-contents
    %h1.review Latest Reviews
  .swiper-container{style:"margin-bottom:30px;"}
    .swiper-wrapper
      .swiper-slide{style:"display:flex;height:auto;justify-content:center;"}
        - @reviews.each do |review|
          .review{style:"min-height:300px;width:20vw;min-width:250px;margin:10px 5px;padding:5px;box-shadow:0 0 4px gray;border-radius:15px;"}
            .review__image{style:"border-bottom:grey 1px solid;height:70%;display:flex;justify-content:center;align-items:center;"}
              = link_to review_path(review.id), data: {"turbolinks" => false} do
                = image_tag review.image, style: "object-fit:contain;max-width:200px; width:auto;"
            .review__brand{style:"height:10%;position:relative;"}
              %h2.brand{style:"position:absolute;bottom:0;font-weight:bold"}
                = review.maker
            .review__item-name{style:"height:10%;position:relative;"}
              %h2.name{style:"position:absolute;bottom:0;font-weight:bold"}
                = review.name
            .review__score
              %h2.score
                = (review.sweetness + review.sourness + review.bitterness + review.sharpness + review.richness)
                ／50点
      .swiper-slide{style:"display:flex;height:auto;justify-content:center;"}
        - @reviews.each do |review|
          .review{style:"min-height:300px;width:20%;min-width:250px;margin:10px 5px;padding:5px;box-shadow:0 0 4px gray;border-radius:15px;"}
            .review__image{style:"border-bottom:grey 1px solid;height:70%;display:flex;justify-content:center;align-items:center;"}
              = link_to review_path(review.id), data: {"turbolinks" => false} do
                = image_tag review.image, style: "object-fit:contain;max-width:200px; width:auto;"
            .review__brand{style:"height:10%;position:relative;"}
              %h2.brand{style:"position:absolute;bottom:0;font-weight:bold"}
                = review.maker
            .review__item-name{style:"height:10%;position:relative;"}
              %h2.name{style:"position:absolute;bottom:0;font-weight:bold"}
                = review.name
            .review__score
              %h2.score
                = (review.sweetness + review.sourness + review.bitterness + review.sharpness + review.richness)
                ／50点
      .swiper-slide{style:"display:flex;height:auto;justify-content:center;"}
        - @reviews.each do |review|
          .review{style:"min-height:300px;width:20%;min-width:250px;margin:10px 5px;padding:5px;box-shadow:0 0 4px gray;border-radius:15px;"}
            .review__image{style:"border-bottom:grey 1px solid;height:70%;display:flex;justify-content:center;align-items:center;"}
              = link_to review_path(review.id) , data: {"turbolinks" => false}do
                = image_tag review.image, style: "object-fit:contain;max-width:200px; width:auto;"
            .review__brand{style:"height:10%;position:relative;"}
              %h2.brand{style:"position:absolute;bottom:0;font-weight:bold"}
                = review.maker
            .review__item-name{style:"height:10%;position:relative;"}
              %h2.name{style:"position:absolute;bottom:0;font-weight:bold"}
                = review.name
            .review__score
              %h2.score
                = (review.sweetness + review.sourness + review.bitterness + review.sharpness + review.richness)
                ／50点
    .swiper-button-prev
    .swiper-button-next
  = render "templete/footer"
%script{type:"text/javascript", src:"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.0/js/swiper.min.js"}
:javascript
  let mySwiper = new Swiper('.swiper-container', {
    autoHeight: true,
    loop: true,
    autoplay: {
      delay: 5000,
      disableOnInteraction: false,
      reverseDirection: false
    },
    navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev'
    }
  });

app/views/reviews/new.html.haml
.wrapper
  = render "templete/header"
  .review-detail
    = form_with model: @review, url: reviews_path, class: "review-form", method: :post do |f|
      = render 'layouts/error', model: f.object
      .review-images
      = f.label :image, "画像", class: "review-label"
      %span.required *
      = f.file_field :image, class:"file"
      .review-score
        .review-score__forms
          .score-box
            %h3.review
              = f.label :name, "製品名", class: "review-label"
              %span.required *
            = f.text_field :name, placeholder: "例) 一番搾り", type: "text", value: "", style: "width:100%; box-sizing:border-box"
          .score-box
            %h3.review
              = f.label :maker, "メーカー", class: "review-label"
              %span.required *
            = f.text_field :maker, placeholder: "例) キリンビール", type: "text", value: "", style: "width:100%; box-sizing:border-box"
          .score-box
            %h3.review
              = f.label :text, "レビュー本文", class: "review-label"
              %span.required *
            = f.text_area :text, placeholder: "例) 男は黙ってサッポロビール", type: "text", value: "", style: "width:100%; min-height:100px; resize:vertical; box-sizing:border-box", cols: "40", rows: "4"
          .range
            %h3.review
              = f.label :sharpness, "キレ", class: "review-label"
              %span.required *
            = f.range_field :sharpness, min: "0", max: "10", step: "1", value: "5", style: "width:95%; box-sizing:border-box", list: "tickmarks"
            %span#value 5
            %datalist{id: "tickmarks"}
              %option{value: "0", label: "0"}
              %option{value: "1"}
              %option{value: "2"}
              %option{value: "3"}
              %option{value: "4"}
              %option{value: "5", label: "5"}
              %option{value: "6"}
              %option{value: "7"}
              %option{value: "8"}
              %option{value: "9"}
              %option{value: "10", label: "10"}
          .range
            %h3.review
              = f.label :richness, "コク", class: "review-label"
              %span.required *
            = f.range_field :richness, min: "0", max: "10", step: "1", value: "5", style: "width:95%; box-sizing:border-box;", list: "tickmarks"
            %span#value 5
          .range
            %h3.review
              = f.label :sourness, "酸味", class: "review-label"
              %span.required *
            = f.range_field :sourness, min: "0", max: "10", step: "1", value: "5", style: "width:95%; box-sizing:border-box", list: "tickmarks"
            %span#value 5
          .range
            %h3.review
              = f.label :bitterness, "苦味", class: "review-label"
              %span.required *
            = f.range_field :bitterness, min: "0", max: "10", step: "1", value: "5", style: "width:95%; box-sizing:border-box", list: "tickmarks"
            %span#value 5
          .range
            %h3.review
              = f.label :sweetness, "甘み", class: "review-label"
              %span.required *
            = f.range_field :sweetness, min: "0", max: "10", step: "1", value: "5", style: "width:95%; box-sizing:border-box", list: "tickmarks"
            %span#value 5
          .submit-btn
            = f.submit "投稿", class: "review-submit"
            .back-btn
              = link_to "戻る", reviews_path
  = render "templete/footer"
:javascript
  var elem = document.getElementsByClassName('range');
    var rangeValue = function (elem, target) {
      return function(evt){
      target.innerHTML = elem.value;
      }
    }
  for(var i = 0, max = elem.length; i < max; i++){
    bar = elem[i].getElementsByTagName('input')[0];
    target = elem[i].getElementsByTagName('span')[0];
    bar.addEventListener('input', rangeValue(bar, target));
  }

app/views/reviews/show.html.haml
.wrapper
  = render "templete/header"
  .review-detail
    .review-detail__box
      .review-info
        %ul
          %li
            %a.twitter-share-button{"data-show-count" => "false", :href => "https://twitter.com/share?ref_src=twsrc%5Etfw"} Tweet
          %li.daytime{style:"display:flex;"}
            %p 投稿日：
            = @review.created_at.strftime("%Y/%m/%d %H:%M")
          %li.nickname{style:"display:flex;"}
            %p 投稿者：
            = @review.user.nickname
      .review-images
        = image_tag @review.image, style: "object-fit:contain; max-width:400px;"
      .review-description
        .score-box
          %h3.review 製品名
          .score-box__text
            = @review.name
        .score-box
          %h3.review メーカー
          .score-box__text
            = @review.maker
        .score-box
          %h3.review レビュー本文
          .score-box__text
            = @review.text
      .review-score
        .score-boxes
          .score-box
            %h3.review キレ
            .score-box__text
              = @review.sharpness
          .score-box
            %h3.review コク
            .score-box__text
              = @review.richness
          .score-box
            %h3.review 酸味
            .score-box__text
              = @review.sourness
          .score-box
            %h3.review 苦味
            .score-box__text
              = @review.bitterness
          .score-box
            %h3.review 甘味
            .score-box__text
              = @review.sweetness
        .score-chart
          %canvas(id="myChart" width="400" height="400")
      .buttons
        - if user_signed_in?
          - if @review.user_id == current_user.id
            .submit-btn
              = link_to "編集する", edit_review_path
            .delete-btn
              = link_to "削除する", review_path, method: :delete
            .back-btn
              = link_to "戻る", reviews_path
          - else
            .back-btn
              = link_to "戻る", reviews_path
        - else
          .back-btn
            = link_to "戻る", reviews_path
  = render "templete/footer"
  %script{:crossorigin => "anonymous", :integrity => "sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=", :src => "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"}
  %script{:async => "", :charset => "utf-8", :src => "https://platform.twitter.com/widgets.js"}
  :javascript
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'radar',
        data: {
          labels: ["キレ", "コク", "酸味", "苦味", "甘味"],
          datasets: [{
            data: gon.score,
            backgroundColor: ['rgba(255, 198, 11, 0.2)'],
            borderColor: ['rgba(255, 198, 11, 1)'],
            borderWidth: 1
            }]
          },
        options: {
          responsive: true,
          legend: {
            display: false
          },
          scale: {
            pointLabels: {
              fontSize: 15
            },
            ticks: {
              stepSize: 1,
              max: 10,
              beginAtZero: true
            }
          }
        }
      });

app/views/search/index.html.haml
.wapper
  = render "templete/header"
  .search-main
    .search-main__box
      = search_form_for @search, url: search_index_path do |f|
        = f.text_field :name_or_maker_or_text_cont, placeholder: '検索するビールを入力...'
        = f.submit ("検索") , class: 'search-btn'
    .results
      - @search_result.each do |review|
        .results__review
          .results__review--image
            = link_to review_path(review.id) , data: {"turbolinks" => false}do
              = image_tag review.image, style: "object-fit:contain;max-width:100px; width:auto;"
          .results__review--text
            %h2.brand{style:"display:flex;"}
              %p メーカー：
              = review.maker
            %h2.name{style:"display:flex;"}
              %p 製品名：
              = review.name
            %h2.score{style:"display:flex;"}
              %p 総合点：
              = (review.sweetness + review.sourness + review.bitterness + review.sharpness + review.richness)
              ／50点
    .pagenation
  = render "templete/footer"

app/views/templete/_footer.html.haml
.footer
  %ul
    %li
      = link_to "ABOUT US", "https://www.wantedly.com/users/101969789"
    %li
      = link_to "利用規約", terms_path

app/views/templete/_header.html.haml
.header
  .header__content 
    = link_to reviews_path, target: "_top" do
      = image_tag 'logo.png', style: "max-height:60px;"
  %ul.menu
    %li.menu__single
      %a.init-bottom{:href => "#"} メニュー
      %ul.menu__second-level
        - if user_signed_in?
          %li
            = link_to "投稿する", new_review_path
          %li
            = link_to "ログアウト", destroy_user_session_path, method: :delete
        - else
          %li
            = link_to "新規登録", new_user_registration_path
          %li
            = link_to "ログイン", new_user_session_path

app/views/top_page/index.html.haml
.wrapper
  = render 'templete/header'
  .main-image
    .main-image__contents
      .main-image__contents--text
        %p きのう何飲んだ？
      .main-image__contents--button
        %ul
          - if user_signed_in?
            %li
              = link_to "ENTER", reviews_path
          - else
            %li
              = link_to "ENTER", reviews_path
            %li
              = link_to "新規登録", new_user_registration_path